# Generated by Django 3.1.2 on 2022-08-12 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedesSociales',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre_red_social', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Participantes',
            fields=[
                ('correo', models.EmailField(editable=False, max_length=254, primary_key=True, serialize=False)),
                ('edad', models.IntegerField(choices=[('A', '18-25'), ('B', '26-33'), ('C', '34-40'), ('D', '41+')])),
                ('sexo', models.CharField(choices=[('%', 'Porcentaje'), ('$', 'cantidad')], max_length=1)),
                ('favorita', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='encuestaRedes.redessociales')),
            ],
        ),
        migrations.CreateModel(
            name='DatosRedes',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('horas', models.FloatField(default=0)),
                ('red_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestaRedes.redessociales')),
            ],
        ),
    ]
